apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: bankapp-namespace
  labels:
    app: bankapp
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keeps the PV after the PVC is deleted
  storageClassName: manual  # Make sure this matches your cluster's default storage class
  hostPath:
    path: /mnt/data/mysql
    
